src/QuizWebApp.Web/Controllers/ScoreController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using QuizWebApp.Data;
using QuizWebApp.Common.Dtos;
using QuizWebApp.Models;
using QuizWebApp.Services.Contracts;
using QuizWebApp.Common.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using QuizWebApp.Sevices.Extensions;

namespace QuizWebApp.Controllers
{
    public class ScoreController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<User> userManager;
        private readonly IScoreService scoreService;
        private readonly ICategoryService categoryService;

        public ScoreController(ApplicationDbContext db, UserManager<User> userManager, IScoreService scoreService, ICategoryService categoryService)
        {
            this.db = db;
            this.userManager = userManager;
            this.scoreService = scoreService;
            this.categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = new CategoryViewModel();

            this.ViewData["categories"] = SelectListGenerator.GetAllCategories(this.categoryService);
            return this.View(viewModel);
        }

        public async Task<IActionResult> AverageScore()
        {
            var currentUser = await this.userManager.GetUserAsync(this.User);

            var viewModel = await this.scoreService.GetTotalScoreCount(currentUser);

            return this.View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> ScoreByCategory(int categoryId)
        {
            var currentUser = await this.userManager.GetUserAsync(this.User);

            var isUserAnsweredQuestionsFromCategory = this.db.Score
                .Where(x => x.CategoryId == categoryId)
                .Where(x => x.UserId == currentUser.Id)
                .Any();

            var viewModel = new ScoreViewModel();

            if (isUserAnsweredQuestionsFromCategory)
            {
                viewModel = await this.scoreService.GetScoreByCategoryId(currentUser, categoryId);
            }
            else
            {
                // Redirect to Quiz Index Action if the user have not answered a question from category
                return  this.RedirectToAction("Index", "Quiz");
            }

            return this.View(viewModel);
        }

        public IActionResult GetLastScore(int correct, int questCount)
        {
            var viewModel = new ScoreViewModel
            {
                CorrectAnswers = correct,
                WrongAnswers = correct - questCount,
            };

            return this.View(viewModel);
        }
    }
}

src/QuizWebApp.Web/Views/Score/AverageScore.cshtml
@model ScoreViewModel
@{
    ViewData["Title"] = "AverageScore Page";
    var correctAnswers = this.Model.CorrectAnswers;
    var wrongAnsweres = this.Model.WrongAnswers;
    var totalAnswersCount = correctAnswers + wrongAnsweres;
    int percentComplete = (int)Math.Round((double)(100 * correctAnswers) / totalAnswersCount);
}

<h3>@totalAnswersCount questions answered in total</h3>
<h2>@percentComplete % of the questions answered correctly</h2>
<canvas id="myChart" height="500" width="500"></canvas>

@section Scripts {
    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ['Wrong Answers', 'Correct Answers',],
                datasets: [{
                    label: '# of Wrong Answers',
                    data: [@wrongAnsweres, @correctAnswers,],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(35, 191, 115, 0.2)',
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(21, 158, 92, 1)',
                    ],
                    borderWidth: 5,

                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: 'white'
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true,
                            fontColor: 'white'
                        }
                    }]
                }
            }
        });
    </script>
}

src/QuizWebApp.Web/Views/Score/GetLastScore.cshtml
@model ScoreViewModel
@{
    ViewData["Title"] = "Last Quiz Results Page";
}

<h2>@Model.CorrectAnswers / 5</h2>

src/QuizWebApp.Web/Views/Score/Index.cshtml
@model CategoryViewModel
@{
    ViewData["Title"] = "Score Page";
    var categories = this.ViewData["categories"] as IEnumerable<SelectListItem>;
    var selectedCategory = string.Empty;
}

<div class="row">
    <div class="mx-auto">
        <div class="mx-auto card-holder">
            <div class="quizCard text-left" style="width: 20em;">
                <div class="row">
                    <div class="form-group col-md-12 text-center">
                        <h3>Check your score by selected Category</h3>
                        <div class="col text-center">
                            <select id="categoryId" asp-items="categories" class="form-control col-md-12">
                            </select>
                            <button onclick="getSearchResult()" type="submit" class="btn btn-success"> Get Results</button>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12 text-center">
                        <h3>Check your all time Score</h3>
                        <div class="col text-center">
                            <form method="get" asp-controller="Score" asp-action="AverageScore">
                                <button class="btn btn-success" type="submit">Check All</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        // Reloading the whole dom. It can be done better if it send request to action which returns _PartialView
        // Fix later
        function getSearchResult() {
            let categoryId = $("#categoryId").val();

            $.ajax({
                type: "GET",
                url: `/Score/ScoreByCategory?categoryId=${categoryId}`,
                contentType: "text/html; charset=utf-8",
                data: {
                },
                success: function (res) {
                    document.location.href = this.url;
                },
                error: function (res) {
                    console.log(res);
                }
            });
        }
    </script>
} 

src/QuizWebApp.Web/Views/Score/ScoreByCategory.cshtml
@model ScoreViewModel
@{
    ViewData["Title"] = "Score Per Category Page";
    var correctAnswers = this.Model.CorrectAnswers;
    var wrongAnsweres = this.Model.WrongAnswers;
    var totalAnswersCount = correctAnswers + wrongAnsweres;
    int percentComplete = (int)Math.Round((double)(100 * correctAnswers) / totalAnswersCount);
}

<h3>@totalAnswersCount questions answered in this category</h3>
<h2>@percentComplete % of the questions answered correctly</h2>
<canvas id="myChart" height="500" width="500"></canvas>

@section Scripts {
    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ['Wrong Answers', 'Correct Answers',],
                datasets: [{
                    label: '# of Answered Questions',
                    data: [@wrongAnsweres, @correctAnswers,],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(35, 191, 115, 0.2)',
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(21, 158, 92, 1)',
                    ],
                    borderWidth: 5,

                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: 'black'
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true,
                            fontColor: 'black'
                        }
                    }]
                }
            }
        });
    </script>
}